name: run-tests
on: [push]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v2
      - run: apt update
      - run: apt install -y curl
      - run: curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
      - run: apt install -y nodejs
      - run: rm bun.lock
      - run: npm i
      - run: npm test
      - name: Run E2E Tests
        env:
          PACKAGE_MANAGER: npm
        run: npm run e2e --verbose